[package]
name = "nes-emulator-rust"
version = "0.1.0"
authors = ["Shuhei Yamashita <b.e7472@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
arrayref = "*"
lazy_static = "1.0"

[dependencies.sdl2]
version = "0.31"
default-features = false